title: Exact Assembly, Software Blog
description: Blog musings about software from the XA team

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
